### Obtener todos los elementos del carrito asociados a un cliente específico
GET https://backend-c-r-production.up.railway.app/cart/1

### Agregar un nuevo elemento al carrito
POST https://backend-c-r-production.up.railway.app/cart/
Content-Type: application/json

{
  "customerId": 1,
  "productoId": 368,
  "producto": "Peluche Nutria",
  "cantidad": 3,
  "IVA": 21.76,
  "precio": 157.76
}

### Actualizar un elemento del carrito por su ID
PUT https://backend-c-r-production.up.railway.app/cart/1/371
Content-Type: application/json

{
  "cantidad": 1
}

### Eliminar un elemento del carrito por su ID
DELETE https://backend-c-r-production.up.railway.app/cart/
Content-Type: application/json

{
  "productoId": 367,
  "customerId": 1
}


### Eliminar todos los elementos del carrito asociados a un cliente específico
DELETE https://backend-c-r-production.up.railway.app/cart/clear/1




### Agregar un nuevo elemento al carrito
POST http://localhost:5000/order/create-order
