### Obtener todos los elementos del carrito asociados a un cliente específico
GET https://backend-c-r-production.up.railway.app/cart/1

### Agregar un nuevo elemento al carrito
POST https://backend-c-r-production.up.railway.app/cart
Content-Type: application/json

{
  "customerId": 1,
  "productoId": 364,
  "producto": "Peluche Stitch Peludito",
  "cantidad": 1,
  "IVA": 83.20,
  "precio": 603.20
}

### Actualizar un elemento del carrito por su ID
PUT https://backend-c-r-production.up.railway.app/cart/1
Content-Type: application/json

{
  "cantidad": 3
}

### Eliminar un elemento del carrito por su ID
DELETE https://backend-c-r-production.up.railway.app/cart/1

### Eliminar todos los elementos del carrito asociados a un cliente específico
DELETE https://backend-c-r-production.up.railway.app/cart/clear
Content-Type: application/json

{
  "customerId": 123
}
